"""add document source_type and content columns

Revision ID: 007
Revises: 006
Create Date: 2026-04-08

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007'
down_revision: str | None = '006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    # 1. 修改 file_path 为可空
    op.alter_column('documents', 'file_path',
               existing_type=sa.String(512),
               nullable=True)

    # 2. 新增 source_type 字段
    op.add_column('documents', sa.Column('source_type', sa.String(8), nullable=False, server_default='file'))

    # 3. 新增 content 字段（TEXT 类型，用于存储文本源内容）
    op.add_column('documents', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust ###
    op.drop_column('documents', 'content')
    op.drop_column('documents', 'source_type')

    # 恢复 file_path 为 NOT NULL（需要先删除 NULL 值）
    op.execute("UPDATE documents SET file_path = '' WHERE file_path IS NULL")
    op.alter_column('documents', 'file_path',
               existing_type=sa.String(512),
               nullable=False)
    # ### end Alembic commands ###
