import json
import logging
import re

from app.adapters.base import AIAdapter

logger = logging.getLogger(__name__)

_CODE_FENCE_RE = re.compile(r"```(?:json)?\s*\n?(.*?)\n?\s*```", re.DOTALL)
_JSON_OBJECT_RE = re.compile(r"\{(?:[^{}]*|\{[^{}]*\})*\}", re.DOTALL)
_JSON_ARRAY_RE = re.compile(r"\[(?:[^\[\]]*|\[[^\[\]]*\])*\]", re.DOTALL)


def _strip_code_fence(text: str) -> str:
    """去除 LLM 常见的 markdown 代码块包裹，只保留 JSON 内容。

    策略：
    1. 优先匹配 markdown 代码块内的内容
    2. 没有代码块时，寻找最外层完整 JSON 结构（对象或数组）
    3. 如果同时匹配到对象和数组，选择匹配更长内容的那个（更可能是完整响应）
    """
    text = text.strip()

    # 1. 优先尝试匹配代码块
    m = _CODE_FENCE_RE.search(text)
    if m:
        return m.group(1).strip()

    # 2. 尝试匹配所有 JSON 对象和数组
    obj_matches = _JSON_OBJECT_RE.findall(text)
    arr_matches = _JSON_ARRAY_RE.findall(text)

    # 都没有匹配到 → 返回原文让 json.loads 报错
    if not obj_matches and not arr_matches:
        return text

    # 只有对象 → 返回第一个完整对象
    if obj_matches and not arr_matches:
        return obj_matches[0]

    # 只有数组 → 返回第一个完整数组
    if arr_matches and not obj_matches:
        return arr_matches[0]

    # 同时有对象和数组匹配：
    # 如果数组匹配包含所有对象匹配，说明是数组格式 [{...}, {...}]
    # 选择长度更长的匹配（通常是外层结构）
    first_obj = obj_matches[0]
    first_arr = arr_matches[0]

    if len(first_arr) >= len(first_obj):
        return first_arr
    return first_obj

_CLEAN_SYSTEM = (
    "You are a professional document proofreader. For the text provided: "
    "1. Fix typos and spelling errors. "
    "2. Remove AI-generated watermarks (e.g. Generated by ChatGPT). "
    "Only do these two things. Do NOT change the meaning, structure, or sentence patterns. "
    "Output the corrected text directly without any explanation."
)

_STRUCTURE_SYSTEM = (
    "You are a document structure analyst. Analyze the document and output a JSON outline. "
    'Format: {"title": "doc title", "sections": [...]}\n'
    "Each section object: {\"level\": N, \"text\": \"...\", \"paragraph_type\": \"heading\"|\"body\", \"children\": [...]}\n"
    "STRICT level rules:\n"
    "- level 1: top-level major sections (e.g. '一、xxx', 'Chapter 1', or the very first tier of headings)\n"
    "- level 2: sub-sections under level 1 (e.g. '（一）xxx', '1.1 xxx')\n"
    "- level 3: sub-sub-sections under level 2 (e.g. '1.', '1.1.1')\n"
    "- level 4: minor sub-headings under level 3\n"
    "- level 0 with paragraph_type=body: body text placed as children of their parent heading\n"
    "A heading's level must always be exactly one more than its parent heading's level. "
    "Never skip levels (e.g. a child of level 1 must be level 2, not level 3). "
    "Preserve ALL original text. Output valid JSON only, no explanation."
)

_STRUCTURE_CORRECTION_PROMPT = (
    "Analyze the document structure and correct heading levels. Input is a JSON list, each item has:\n"
    "- i: index\n"
    "- t: type (heading/body/table/image)\n"
    "- l: level (heading has initial level, body/table/image are 0)\n"
    "- text: only heading has, for level judgment\n\n"
    "Level rules:\n"
    "- level 1: '一、xxx', '第 x 章', '阶段 X', major sections\n"
    "- level 2: '1.1 xxx', '（一）xxx', '第 x 节', sub-sections\n"
    "- level 3: '1.1.1 xxx', '（1）xxx'\n"
    "- level 4: minor headings\n\n"
    "STRICT RULES (must follow):\n"
    "- Headings must be hierarchical: a level N heading can only have level N+1 children\n"
    "- NEVER skip levels (e.g., level 1 -> level 4 is invalid, adjust to level 2)\n"
    "- If a heading's level jumps, adjust it to be at most (previous_heading_level + 1)\n"
    "- **Headings with the same text pattern MUST have the same level**\n"
    "  - Example: '阶段一', '阶段二', '阶段三' should all be the same level\n"
    "  - Example: '1.1 xxx', '1.2 xxx', '1.3 xxx' should all be the same level\n"
    "  - Recognize number sequences: Chinese numerals (一、二、三...) and Arabic numerals (1, 2, 3...) indicate same level\n"
    "\nOutput: Corrected JSON list, same length and order, only correct heading level values.\n"
    "Keep body/table/image l=0 unchanged.\n\nInput:\n"
)

_HEADING_IDENTIFICATION_SYSTEM = (
    "You are a document structure analyst. Analyze the document text and identify "
    "all headings and their levels.\n\n"
    "Input format: Each line represents a paragraph. Formatting hints are marked as:\n"
    "- [B]...[/B]: Bold text\n"
    "- [H]...[/H]: Heiti (black bold) font\n"
    "- Plain text: normal body text\n\n"
    "Output JSON list, each item:\n"
    '{\n  "index": N,       // Line number (0-based)\n  "is_heading": true/false,\n  "level": 1-4,       // Only if is_heading=true, otherwise omit\n  "confidence": "high"|"medium"|"low"\n}\n\n'
    "Level identification rules:\n"
    "- level 1: Top-level major sections (一、xxx, 第 x 章，阶段 X, first tier headings)\n"
    "- level 2: Sub-sections under level 1 (1.1 xxx, （一）xxx, 第 x 节)\n"
    "- level 3: Sub-sub-sections under level 2 (1.1.1 xxx, （1）xxx)\n"
    "- level 4: Minor sub-headings under level 3\n\n"
    "Clues to identify headings:\n"
    "- Numbering prefixes: 一、, 1.1, （一）, 第 x 章，1., a.\n"
    "- Short text (≤20 chars) with [B] or [H] formatting\n"
    "- Standalone short paragraphs that look like section breaks\n"
    "- Semantic section breaks (topic changes)\n\n"
    "Important:\n"
    "- A heading at level N can only have children at level N+1\n"
    "- Headings with similar numbering patterns should have the same level\n"
    "- Output ALL paragraphs, not just headings (is_heading=false for body text)\n\n"
    "Output valid JSON array only, no explanation."
)

# 百炼套餐专属 Base URL
_CODING_PLAN_URL = "https://coding.dashscope.aliyuncs.com/v1"
_DEFAULT_MODEL = "qwen3.6-plus"


class QwenAdapter(AIAdapter):
    """阿里云百炼 Coding Plan 适配器。

    使用 OpenAI 兼容协议调用，通过专属 Base URL 访问套餐模型。
    """

    def __init__(self, api_key: str, model_name: str = "") -> None:
        self._api_key = api_key
        self._model_name = model_name or _DEFAULT_MODEL

    async def clean_text(self, text: str) -> str:
        import openai  # noqa: PLC0415

        client = openai.AsyncOpenAI(
            api_key=self._api_key,
            base_url=_CODING_PLAN_URL,
        )
        resp = await client.chat.completions.create(
            model=self._model_name,
            messages=[
                {"role": "system", "content": _CLEAN_SYSTEM},
                {"role": "user", "content": text},
            ],
        )
        return resp.choices[0].message.content or ""

    async def extract_structure(self, text: str) -> dict[str, object]:
        import openai  # noqa: PLC0415

        client = openai.AsyncOpenAI(
            api_key=self._api_key,
            base_url=_CODING_PLAN_URL,
            timeout=300.0,
        )
        resp = await client.chat.completions.create(
            model=self._model_name,
            messages=[
                {"role": "system", "content": _STRUCTURE_SYSTEM},
                {"role": "user", "content": text},
            ],
        )
        raw = resp.choices[0].message.content or "{}"
        raw = _strip_code_fence(raw)
        try:
            result: dict[str, object] = json.loads(raw)
        except json.JSONDecodeError as exc:
            logger.error("Qwen returned invalid JSON: %s", raw[:200])
            raise ValueError("AI returned invalid structure JSON") from exc
        return result

    async def correct_structure(self, sections: list[dict]) -> list[dict]:
        """AI 修正文档结构层级。"""
        import openai  # noqa: PLC0415

        simplified = []
        for i, s in enumerate(sections):
            item = {
                "i": i,
                "t": s.get("paragraph_type", "body"),
                "l": s.get("level", 0),
            }
            if s.get("paragraph_type") == "heading":
                item["text"] = s.get("text", "")[:80]
            simplified.append(item)

        input_json = json.dumps(simplified, ensure_ascii=False, separators=(",", ":"))
        prompt = _STRUCTURE_CORRECTION_PROMPT + input_json

        logger.info(
            "AI correct_structure input: %d items, %d chars",
            len(simplified),
            len(input_json),
        )

        client = openai.AsyncOpenAI(
            api_key=self._api_key,
            base_url=_CODING_PLAN_URL,
            timeout=300.0,
        )
        resp = await client.chat.completions.create(
            model=self._model_name,
            messages=[{"role": "user", "content": prompt}],
        )

        raw = resp.choices[0].message.content or "[]"
        raw = _strip_code_fence(raw)
        logger.info("AI correct_structure raw response: %d chars", len(raw))

        try:
            corrected: list[dict] = json.loads(raw)
            logger.info("AI correct_structure parsed JSON: %d items", len(corrected))
        except json.JSONDecodeError as exc:
            logger.error("Qwen returned invalid JSON: %s", raw[:200])
            raise ValueError("AI 返回了无效的 JSON 结构") from exc

        if len(corrected) != len(sections):
            logger.warning(
                "AI returned %d items, expected %d", len(corrected), len(sections)
            )

        # 构建 level 映射
        level_map = {}
        for item in corrected:
            if isinstance(item, dict):
                idx = item.get("i", item.get("index"))
                lvl = item.get("level", item.get("l"))
                if idx is not None and lvl is not None:
                    level_map[idx] = lvl

        logger.info("AI correct_structure level_map: %d entries", len(level_map))

        # 映射回原始 sections（浅拷贝，不 deepcopy 大对象）
        result = []
        for i, s in enumerate(sections):
            new_section = dict(s)
            if s.get("paragraph_type") == "heading" and i in level_map:
                new_level = level_map[i]
                if new_level != s.get("level"):
                    new_section["level"] = new_level
            result.append(new_section)

        logger.info("AI correct_structure done: %d items", len(result))
        return result

    async def identify_headings(self, formatted_text: str) -> list[dict]:
        """AI 识别文档标题（基于语义理解和格式提示）。

        Args:
            formatted_text: 带格式标记的文档文本，每行一个段落
                格式：[B]加粗文本 [/B], [H] 黑体文本 [/H]

        Returns:
            list[dict]: 每段的结构分析结果
                [{"index": 0, "is_heading": true, "level": 1, "confidence": "high"}, ...]
        """
        import openai  # noqa: PLC0415

        client = openai.AsyncOpenAI(
            api_key=self._api_key,
            base_url=_CODING_PLAN_URL,
            timeout=300.0,
        )

        # 限制输入长度，避免 token 超限
        lines = formatted_text.split('\n')
        max_lines = 200  # 最多处理 200 行
        if len(lines) > max_lines:
            logger.warning("Input too long (%d lines), truncating to %d lines", len(lines), max_lines)
            lines = lines[:max_lines]
        truncated_text = '\n'.join(lines)

        logger.info("AI identify_headings input: %d lines, %d chars", len(lines), len(truncated_text))

        resp = await client.chat.completions.create(
            model=self._model_name,
            messages=[
                {"role": "system", "content": _HEADING_IDENTIFICATION_SYSTEM},
                {"role": "user", "content": truncated_text},
            ],
        )

        raw = resp.choices[0].message.content or "[]"
        raw = _strip_code_fence(raw)
        logger.info("AI identify_headings raw response: %d chars", len(raw))

        try:
            result: list[dict] = json.loads(raw)
            logger.info("AI identify_headings parsed JSON: %d items", len(result))
        except json.JSONDecodeError as exc:
            logger.error("Qwen returned invalid JSON: %s", raw[:200])
            raise ValueError("AI 返回了无效的 JSON 结构") from exc

        return result
